name: AppImage build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out repo
    - uses: actions/checkout@master
    # Install deps
    - name: Install required deps
      run: |
        sudo apt update
        sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev libfuse2
        python3 -m pip install virtualenv
    # Create AppDir
    - name: Create AppDir
      run: |
        mkdir test-pywebview.AppDir
        cd test-pywebview.AppDir
        cp ../appimage/* .
        mkdir -p ./usr/src
        cp ../main.py ./usr/src
    - name: Create virtual environment
      run: |
        cd test-pywebview.AppDir
        virtualenv --python=python3 ./usr
        source ./usr/bin/activate
        pwd
    - name: Install pip dependencies
      run: |
        cd test-pywebview.AppDir
        pip install -r ../requirements.txt
    - name: Build AppImage
      run: |
        export ARCH=$(uname -m)
        curl -L -o appimagetool-$ARCH.AppImage https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage
        chmod a+x appimagetool-$ARCH.AppImage
        ./appimagetool-$ARCH.AppImage ./test-pywebview.AppDir
        rm appimagetool-$ARCH.AppImage
    - name: Upload artifacts
      run: |
        curl -T *.AppImage https://temp.sh
