name: AppImage build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out repo
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt install python3 python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0 libgirepository1.0-dev libcairo2-dev
    - uses: AppImageCrafters/build-appimage@master
      with:
        recipe: "./appimage/AppImageBuilder.yml"
    - name: Upload artifacts
      run: |
        curl -T *.AppImage https://temp.sh
